spring.main.web-application-type=none
logging.level.root=WARN
logging.level.com.rca=INFO

rca.ingestion-url=http://localhost:8081/api/v1/rca/analyze
rca.query-url=http://localhost:8083/api/v1/rca/jobs